### ISSUE TITLE
Login widget redirect doesn't accept external URLs

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#20]
@jameslovejoy Looks like the redirect option requires a relative URL to be specified. If an external URL is specified it's appended to the end. In my case I'm trying to redirect users to a forum after they login.

**Comment by jameslovejoy** [comment]
This was by design (following Daniel's comment in the [Pivotal story](https://www.pivotaltracker.com/story/show/41333975)) that it should only accept relative URLs and not full URLs.

If we do want to accept full URLs, it's an easy change.  All it takes is changing `location.pathname` to `location.href` on [line 214 in sparkart.js](https://github.com/SparkartGroupInc/sparkart.js/blob/master/sparkart.js#L214).

**Comment by pushred** [comment]
OK I'm going to use a redirect to handle this.
